package arthurpaivamuniz.conversor;

import java.awt.Label;
import java.text.DecimalFormat;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;

/**
 *
 * @author arthur
 */
public class ConversorJava extends javax.swing.JFrame {

    /**
     * Creates new form ConversorJava
     */
    public ConversorJava() {
        initComponents();
    }

    /* Não é a melhor opção existente, porém sou iniciante e não sei
     * consumir dados de uma API para pegar esses valores.
    */
    double bitcoin = 120.770; //valores arredondados 
    double dolar = 5.44;
    double euro = 5.51;   
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jEditorPane1 = new javax.swing.JEditorPane();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        valorReais = new javax.swing.JTextField();
        lblResBit = new javax.swing.JLabel();
        lblResEur = new javax.swing.JLabel();
        bitBtn = new javax.swing.JToggleButton();
        dolBtn = new javax.swing.JToggleButton();
        euroBtn = new javax.swing.JToggleButton();
        lblResDol = new javax.swing.JLabel();
        creditsBtn = new javax.swing.JToggleButton();
        lblGithub = new javax.swing.JLabel();
        lblInstagram = new javax.swing.JLabel();
        lblLinkedin = new javax.swing.JLabel();

        jScrollPane1.setViewportView(jEditorPane1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel2.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jLabel2.setText("Conversor de Moedas ");

        jLabel1.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel1.setText("Valor: R$ ");

        valorReais.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                valorReaisActionPerformed(evt);
            }
        });

        lblResBit.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        lblResBit.setForeground(new java.awt.Color(204, 153, 0));

        lblResEur.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        lblResEur.setForeground(java.awt.Color.orange);

        bitBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/arthurpaivamuniz/conversor/images/bitnew.png"))); // NOI18N
        bitBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bitBtnActionPerformed(evt);
            }
        });

        dolBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/arthurpaivamuniz/conversor/images/dolnew.png"))); // NOI18N
        dolBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dolBtnActionPerformed(evt);
            }
        });

        euroBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/arthurpaivamuniz/conversor/images/euronew.png"))); // NOI18N
        euroBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                euroBtnActionPerformed(evt);
            }
        });

        lblResDol.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        lblResDol.setForeground(java.awt.Color.green);

        creditsBtn.setText("Créditos");
        creditsBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                creditsBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(creditsBtn)
                .addGap(34, 34, 34))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblGithub)
                            .addComponent(lblInstagram)
                            .addComponent(lblLinkedin)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(46, 46, 46)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 288, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel1)
                                        .addGap(29, 29, 29)
                                        .addComponent(valorReais, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(lblResBit, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(158, 158, 158))
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                            .addComponent(bitBtn)
                                            .addGap(46, 46, 46)
                                            .addComponent(dolBtn))))
                                .addGap(31, 31, 31))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(lblResDol, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(68, 68, 68)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblResEur, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(euroBtn))))
                .addContainerGap(55, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel2)
                .addGap(57, 57, 57)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(valorReais, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(118, 118, 118)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(euroBtn)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(bitBtn)
                        .addComponent(dolBtn)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblResBit)
                .addGap(9, 9, 9)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblResEur, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblResDol, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(13, 13, 13)
                .addComponent(lblGithub)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblInstagram)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblLinkedin)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 93, Short.MAX_VALUE)
                .addComponent(creditsBtn)
                .addGap(22, 22, 22))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    private void valorReaisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_valorReaisActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_valorReaisActionPerformed

    private void bitBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bitBtnActionPerformed
        // TODO add your handling code here:
        float real = Float.parseFloat(valorReais.getText());
        float valorBit = (float) (real / bitcoin);
        if (bitBtn.isSelected()) {
            lblResBit.setText(String.valueOf(valorBit).format("%2f", valorBit));
        } else {
            lblResBit.setText(" ");
        }
    }//GEN-LAST:event_bitBtnActionPerformed

    private void dolBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dolBtnActionPerformed
        // TODO add your handling code here:
        float real = Float.parseFloat(valorReais.getText());
        float valorDol = (float) (real / dolar);
        if (dolBtn.isSelected()) {
            lblResDol.setText(String.valueOf(valorDol).format("%2f", valorDol));
        } else {
            lblResDol.setText(" ");
        }
    }//GEN-LAST:event_dolBtnActionPerformed

    private void euroBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_euroBtnActionPerformed
        // TODO add your handling code here:
        float real = Float.parseFloat(valorReais.getText());
        float valorEur = (float) (real / euro);
        if (euroBtn.isSelected()) {
            lblResEur.setText(String.valueOf(valorEur).format("%2f", valorEur));
        } else {
            lblResEur.setText(" ");
        }
    }//GEN-LAST:event_euroBtnActionPerformed

    private void creditsBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_creditsBtnActionPerformed
        // TODO add your handling code here:
        if (creditsBtn.isSelected()) {
            lblGithub.setText("Github: arthur201306");
            lblInstagram.setText("Instagram: arthur2331");
            lblLinkedin.setText("LinkedIn: https://www.linkedin.com/in/arthur-paiva-muniz-18908a219/");
        } else {
            lblGithub.setText(" ");
            lblInstagram.setText(" ");
            lblLinkedin.setText(" ");
        }
    }//GEN-LAST:event_creditsBtnActionPerformed
   
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ConversorJava.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ConversorJava.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ConversorJava.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ConversorJava.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ConversorJava().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton bitBtn;
    private javax.swing.JToggleButton creditsBtn;
    private javax.swing.JToggleButton dolBtn;
    private javax.swing.JToggleButton euroBtn;
    private javax.swing.JEditorPane jEditorPane1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblGithub;
    private javax.swing.JLabel lblInstagram;
    private javax.swing.JLabel lblLinkedin;
    private javax.swing.JLabel lblResBit;
    private javax.swing.JLabel lblResDol;
    private javax.swing.JLabel lblResEur;
    private javax.swing.JTextField valorReais;
    // End of variables declaration//GEN-END:variables
}
